---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- directory: Applications/book-shop
  children:
  - name: book-shop
    type: udm.Application
    lastVersion: 1.0.0-0.0.1
    children:
    - name: 1.0.0-0.0.1
      type: udm.DeploymentPackage
      deployables:
      - name: secrets
        type: k8s.ResourcesFile
        file: !file "../kubernetes/secrets.yml"
      - name: database-volume
        type: k8s.ResourcesFile
        file: !file "../kubernetes/database-volume-k3s.yml"
      - name: database-deployment
        type: k8s.ResourcesFile
        file: !file "../kubernetes/database-deployment.yml"
      - name: database-service
        type: k8s.ResourcesFile
        file: !file "../kubernetes/database-service.yml"
      - name: bookstore-configmap
        type: k8s.ResourcesFile
        file: !file "../kubernetes/bookstore-configmap.yml"
      - name: bookstore-deployment
        type: k8s.ResourcesFile
        file: !file "../kubernetes/bookstore-deployment.yml"
        createOrder: 63
      - name: bookstore-service
        type: k8s.ResourcesFile
        file: !file "../kubernetes/bookstore-service.yml"
      - name: bookstore-ingress-k3s.yml
        type: k8s.ResourcesFile
        file: !file "../kubernetes/bookstore-ingress-k3s.yml"


