apiVersion: xl-deploy/v1
kind: Deployment
spec:
    package: !format "Applications/book-shop/book-shop/%version%"
    environment: Environments/book-shop/book.dev
    onSuccessPolicy: ARCHIVE
    #orchestrators:
    #  - sequential-by-deployed