version: "2"
services:
  xl-deploy:
    image: xebialabs/xl-deploy:9.8.0
    container_name: xl-deploy
    ports:
     - "4516:4516"
    volumes:
     - ./plugins:/opt/xebialabs/xl-deploy-server/plugins
    environment:
     - ADMIN_PASSWORD=admin
     - ACCEPT_EULA=Y


